In [1]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix



In [2]:
mnist = fetch_openml("mnist_784")
X = mnist.data.astype('float32')
y = mnist.target.astype('int')

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [4]:
mlp_classifier = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=10, random_state=42)

In [5]:
mlp_classifier.fit(X_train, y_train)


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=10, random_state=42)

In [6]:
y_pred = mlp_classifier.predict(X_test)


In [7]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.9412857142857143


In [8]:
print(y_pred)

[8 4 5 ... 2 7 1]


In [9]:
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.95      0.95      1343
           1       0.98      0.98      0.98      1600
           2       0.94      0.91      0.92      1380
           3       0.93      0.93      0.93      1433
           4       0.95      0.93      0.94      1295
           5       0.94      0.94      0.94      1273
           6       0.96      0.96      0.96      1396
           7       0.94      0.96      0.95      1503
           8       0.91      0.92      0.92      1357
           9       0.91      0.93      0.92      1420

    accuracy                           0.94     14000
   macro avg       0.94      0.94      0.94     14000
weighted avg       0.94      0.94      0.94     14000

Confusion Matrix:
 [[1281    0   12    1    5    2    8    5    8   21]
 [   0 1568    4    5    3    6    2    2    8    2]
 [  19    9 1253   27    5    1   12   18   23   13]
 [   6    2   21 1327    2   28    1   